
- name: configure bash profile for users
  template:
    src: bash/bash_profile.j2
    dest: "{{item.home}}/.bash_profile"
  with_items: "{{ users }}"

- name: configure bashrc for users
  template:
    src: bash/bashrc.j2
    dest: "{{item.home}}/.bashrc"
  with_items: "{{ users }}"
