
- name: configure /etc/sudoers.d/wheel
  template:
    src: sudoers/wheel.j2
    dest: /etc/sudoers.d/wheel
    mode: 0440
    owner: root
    group: root

- name: disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication .*'
    line: 'PasswordAuthentication no'
  notify:
  - restart sshd

- name: disable SSHroot logins
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin .*'
    line: 'PermitRootLogin no'
  notify:
  - restart sshd

- name: configure firewalld public interfaces
  firewalld:
    zone: public
    interface: "{{item}}"
    permanent: true
    state: enabled
  with_items: "{{firewalld.public_interfaces}}"

- name: configure firewalld trusted interfaces
  firewalld:
    zone: trusted
    interface: "{{item}}"
    permanent: true
    state: enabled
  with_items: "{{firewalld.trusted_interfaces}}"

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
