
- name: Install Sensu Core repo
  yum_repository:
    name: sensu_core
    description: Sensu core repo
    file: sensu
    baseurl: https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
    gpgkey: https://repositories.sensuapp.org/yum/pubkey.gpg
    gpgcheck: yes
  when: sensu.master

- name: Install Uchiwa dashboard repo
  yum_repository:
    name: uchiwa
    description: Sensu Uchiwa dashboard repo
    file: sensu
    baseurl: https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
    gpgcheck: no
  when: sensu.master

- name: Install redis
  yum:
    state: present
    name: redis
  when: sensu.master and sensu.transport == 'redis'

- name: enable redis for sensu
  service:
    name: redis
    enabled: yes
    state: started
  when: sensu.master and sensu.transport == 'redis'

- name: Install sensu
  yum:
    state: present
    name:
      - sensu
      - uchiwa
  when: sensu.master

- name: Install sensu-go-agent
  yum:
    state: present
    name:
      - sensu-go-agent
  when: sensu.agent

- name: allow uchiwa access in firewall
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
