
- name: install yarn repository
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    mode: 0644
    owner: root
    group: root

- name: Install yarn
  yum:
    state: present
    name:
      - yarn


