
- name: add docker-ce apt signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: configure docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present
    filename: docker-ce

- name: add docker packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - docker-compose
