
# Roles to configure
roles:
  - postgresql
  - python
  - node
  - sensu
  - yarn

# Sensu
sensu:
  agent: false
  master: false
  transport: redis

# Postgresql
postgresql:
  version: 11
  repository: https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm
  client: yes
  devel: yes
  server: yes

# Node versions
node:
  repository: https://rpm.nodesource.com/pub_10.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm

# Python 3 versions to add to centos 7
python:
  version: 36
  link_version: 3.6

# Packages to install in centos 7
packages:
  - ansible
  - git
  - net-tools
  - pass
  - rsync
  - vim

# Users to create
users:
  - name: hile
    comment: Ilkka Tuohela
    uid: 1085
    home: /home/hile
    groups:
      - wheel
    ssh_public_key: ~/.ssh/id_rsa.pub
