
- name: restart postgresql
  service:
    name: "postgresql-{{postgresql.version}}"
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart sensu-server
  service:
    name: sensu-server
    state: restarted

- name: restart sensu-client
  service:
    name: sensu-client
    state: restarted
