
- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart postgresql
  service:
    name: "postgresql-{{postgresql.version}}"
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
